### ISSUE TITLE
Deploy via github actions lukt niet

### ISSUE THREAD

**Issue by AFIRO** [AFIRO/gamenerd-fe#1]
Beste,

Ik ben klaar met beide projecten. DB en back end draaien al online, maar de fe krijg ik langs geen meter gedeployed met onderstaande action. Ongeacht wat ik doe, klaagt hij over syntaxis fouten. Is het mogelijk om te helpen? Ik weet uit ervaring dat Yaml heel kieskeurig is, maar hij wil deze echt niet pakken.

name: CI

on:
	push:
		branches: [ main ]
	pull_request:
		branches: [ main ]

jobs:
	build:
		runs-on: ubuntu-latest
		env:
			REACT_APP_BACKEND_BASE_URL: https://pietervdh-budget-api.herokuapp.com/api/

		steps:
			- name: Checkout 🛎️
				uses: actions/checkout@v2.3.1

			- name: Install and Build 🔧 
				run: |
					yarn install --frozen-lockfile
					yarn build

			- name: Deploy 🚀
				uses: JamesIves/github-pages-deploy-action@4.1.7
				with:
					branch: gh-pages # The branch the action should deploy to.
					folder: build # The folder the action should deploy.

**Comment by AFIRO** [comment]
Dit is letterlijk gecopypaste vanuit de cursus met enkel de URL aangepast.
![image](https://user-images.githubusercontent.com/74510849/199855489-8370318b-d548-4e4e-97f4-9e44ef4cd866.png)

**Comment by Pieter-hogent** [comment]
Ik ben uw vraag niet vergeten, en kom er weldra op terug (dat hoofdstuk staat nog op, en is nog, "work in progress"; misschien is er wel iets veranderd, zelf nog niet geprobeerd dit semester)

**Comment by AFIRO** [comment]
Beste,

Geen enkel probleem hoor.  Ik heb mijn site al gedeployed met Vercel dus het is zeker niet blocking.

Github Actions is gewoon alsmaar meer relevant in het werkveld dus het is vooral uit interesse en voor mijn job dat ik het ook op die manier wil kunnen.
